spring:
  profiles:
    group:
      dev:
        - h2
      prod:
        - mysql

---

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

Python:
  url: "http://localhost:5000/"
CORS:
  urls: "https://stately-florentine-57e556.netlify.app/"

---
spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:tcp://localhost/~/mbtigram
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

---
#
#spring:
#  config:
#    activate:
#      on-profile: mysql
#
#  datasource:
#    url: jdbc:mysql://gooroom-db.cwfs4j4gmmfx.ap-northeast-2.rds.amazonaws.com:3306/gooroom_db
#    username: p3j1
#    password: wjdghkswldkstndudwnstj
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#      default_batch_fetch_size: 100
#    properties:현
#      hibernate:
#        format_sql: true